/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloNativeTest */

#ifndef _Included_HelloNativeTest
#define _Included_HelloNativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloNativeTest
 * Method:    greeting
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloNativeTest_greeting
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
